# Generated by Django 4.2.18 on 2025-02-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('la2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=256, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('server', models.CharField(choices=[('x2', 'X2'), ('x50', 'X50'), ('x1200', 'X1200')], max_length=5, verbose_name='Server')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
